#title: willowolf # automatically fetched from the project name
description: the wills of rathewolf #the altruistic desires of rathewolf: his wills, manifested digitally.

# theme: jekyll-theme-tactile # minima is the default theme

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll#further-reading
#   - set remote_theme
#   - can use any theme found on gitHub, the value is [user-name]/[theme name]
#   - see https://github.com/topics/jekyll-theme

# title: will o' wolf # will-o'-wolf? # the domain name 'willowolf' is the default; keep 'willowolf' for consistency
remote_theme: piharpi/jekyll-klise # see jekyll.txt in your notes for more themes
# changing the theme seems to take a long time for GitHub

#minima:
#  skin: dark #solarized
