remote_theme: rahil627/minima-customized-jekyll-theme

# standard
title: 'willowolf: the spiritual wills of rathewolf' # automatically fetched from the project name
#title: will o' wolf # will-o'-wolf? # the domain name 'willowolf' is the default; keep 'willowolf' for consistency and SEO purposes
#description: 'the spiritual wills of rathewolf' #the altruistic desires of rathewolf: his wills, manifested digitally.

# theme vars
# minimal/minimalist theme
# color-scheme: auto-default-dark

minima:
  skin: dark

# custom
title-short: willowolf
footer: a project by <a href="https://rathewolf.com">rathewolf</a>
nav:
  1: "<a href='https://natural.willowolf.com'>natural<a>"
  2: "<a href='https://experimental.willowolf.com'>experimental<a>"
  3: "<a href='https://fighting.willowolf.com'>fighting<a>"
#  4: "<a href='https://philosophical.willowolf.com'>philosophical<a>"
