# build vars
remote_theme: rahil627/minima-customized

# standard vars
title: 'willowolf: the spiritual wills of rathewolf' # automatically fetched from the project name
#title: will o' wolf # will-o'-wolf? # the domain name 'willowolf' is the default; keep 'willowolf' for consistency and SEO purposes
#description: 'the spiritual wills of rathewolf' #the altruistic desires of rathewolf: his wills, manifested digitally.

# theme vars
minima:
  skin: dark

# custom vars
title-short: willowolf
footer:
  left: a project by <a href="https://rathewolf.com">rathewolf</a>
  
