#theme: jekyll-theme-minimal # minima is the default theme
#remote_theme: rahil627/jekyll-klise # piharpi/jekyll-klise # has an error # see jekyll.txt in your notes for more themes
remote_theme: rahil627/minimalist-jekyll-theme # on mobile devices, becomes two-column when the device turned sideways

# standard
title: 'willowolf: the spiritual wills of rathewolf' # automatically fetched from the project name
#title: will o' wolf # will-o'-wolf? # the domain name 'willowolf' is the default; keep 'willowolf' for consistency and SEO purposes
#description: 'the spiritual wills of rathewolf' #the altruistic desires of rathewolf: his wills, manifested digitally.

# minimal/minimalist
color-scheme: auto-default-dark

# custom
title-short: 'willowolf'
nav:
  1: "<a href='https://natural.willowolf.com'>natural<a>"
  2: "<a href='https://experimental.willowolf.com'>experimental<a>"
  3: "<a href='https://fighting.willowolf.com'>fighting<a>"
#  4: "<a href='https://philosophy.willowolf.com'>philosophy<a>"
