#title: willowolf # automatically fetched from the project name
description: the wills of rathewolf #the altruistic desires of rathewolf: his wills, manifested digitally.

# theme: jekyll-theme-tactile # minima is the default theme

# title: will o' wolf # will-o'-wolf? # the domain name 'willowolf' is the default; keep 'willowolf' for consistency and SEO purposes
remote_theme: piharpi/jekyll-klise # see jekyll.txt in your notes for more themes
# changing the theme seems to take a long long time for GitHub...

#minima:
#  skin: dark #solarized
